#!/bin/bash

#
# Repository Post-Receive Hook
#

set -e
set -u

# TODO snapshot=/mit/6.HANDX/path/to/repo-snapshot

self="$1" # meta-hook supplies original script name
subdir="${self%scripts/repo-post-receive-hook}"
# TODO or if multiple hooks: subdir="${self%scripts/*-hooks/*}"
src="${subdir%/}"

# be helpful to someone debugging this script
if [ -z "$GIT_DIR" -o -z "$self" ]; then
  echo "Usage: echo <oldrev> <newrev> <branch> | GIT_DIR=<dir> $0 <path/to/self>"
  exit 1
fi

# only continue with updates to master
master='refs/heads/master'
while read -r oldrev newrev branch; do
  if [ "$branch" == "$master" ]; then break; fi
done
if [ "$branch" != "$master" -o -z "$newrev" ]; then exit 0; fi

# if this script will update the snapshot...
#echo Updating snapshot in $snapshot
#GIT_WORK_TREE="$snapshot" git checkout -f

# find and deliver updated handouts
git diff --name-only "$oldrev" "$newrev" |
perl -lne "/$subdir"'(.*)\/handout\// && print $1' |
sort | uniq |
while read -r dir; do
  "$snapshot/$src/scripts/deliver-handouts-athena" "$dir"
done
