#!/bin/bash

#
# Repository Post-Receive Hook
#

# TODO snapshotdir=/mit/6.HANDX/path/to/repo-snapshot

set -e
set -u

# meta-hook supplies original script name
self="$1"

semester="${self%/scripts/repo-post-receive-hook}"

# be helpful to someone debugging this script
if [ -z "$GIT_DIR" -o -z "$self" ]; then
  echo "Usage: echo <oldrev> <newrev> <branch> | GIT_DIR=<dir> $0 <path/to/self>"
  exit 1
fi

master="refs/heads/master"

while read -r oldrev newrev branch; do
  if [ "$branch" == "$master" ]; then
    break
  fi
done

if [ "$branch" != "$master" -o -z "$newrev" ]; then
  exit 0
fi

# update our snapshot of master
echo Updating snapshot in $snapshotdir
GIT_WORK_TREE="$snapshotdir" git checkout -f

# deploy handouts to the web
git diff --name-only "$oldrev" "$newrev" |
perl -lne "/$semester"'\/(.*)\/handout\// && print $1' |
sort | uniq |
while read -r dir; do
  "$snapshotdir/$semester/scripts/deliver-handouts-athena" "$dir"
done
